//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crisis.Core.Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crisis.Core.Lang.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RETURN.
        /// </summary>
        internal static string _return {
            get {
                return ResourceManager.GetString("_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à After.
        /// </summary>
        internal static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Before.
        /// </summary>
        internal static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à With what category you want to work : .
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to specify a ending chain ?.
        /// </summary>
        internal static string ChangeEndblockPattern {
            get {
                return ResourceManager.GetString("ChangeEndblockPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Write the end string :.
        /// </summary>
        internal static string ChangeEndblockPattern1 {
            get {
                return ResourceManager.GetString("ChangeEndblockPattern1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to specify a starting chain ?.
        /// </summary>
        internal static string ChangeStartblockPattern {
            get {
                return ResourceManager.GetString("ChangeStartblockPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Write the starting string :.
        /// </summary>
        internal static string ChangeStartblockPattern1 {
            get {
                return ResourceManager.GetString("ChangeStartblockPattern1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CHARACTER LOWERCASE.
        /// </summary>
        internal static string CHARACTERLOWERCASE {
            get {
                return ResourceManager.GetString("CHARACTERLOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CHARACTER UPPERCASE.
        /// </summary>
        internal static string CHARACTERUPPERCASE {
            get {
                return ResourceManager.GetString("CHARACTERUPPERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CARACTERE MAJUSCULES &amp; MINUSCULES.
        /// </summary>
        internal static string CHARACTERUPPERCASELOWERCASE {
            get {
                return ResourceManager.GetString("CHARACTERUPPERCASELOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Write the pattern to your choice : .
        /// </summary>
        internal static string charset {
            get {
                return ResourceManager.GetString("charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CREATE WORDLIST.
        /// </summary>
        internal static string createWordlist {
            get {
                return ResourceManager.GetString("createWordlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CYRILLIC.
        /// </summary>
        internal static string cyrillic {
            get {
                return ResourceManager.GetString("cyrillic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EXIT.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Increment.
        /// </summary>
        internal static string Increment {
            get {
                return ResourceManager.GetString("Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Want to mix the pattern ?.
        /// </summary>
        internal static string MixPatern {
            get {
                return ResourceManager.GetString("MixPatern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In  what  folder do you want the backup files?.
        /// </summary>
        internal static string PathOfBuckupFiles {
            get {
                return ResourceManager.GetString("PathOfBuckupFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to confirm backup in.
        /// </summary>
        internal static string PathOfBuckupFiles1 {
            get {
                return ResourceManager.GetString("PathOfBuckupFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pattern for Crunch.
        /// </summary>
        internal static string PatternforCrunch {
            get {
                return ResourceManager.GetString("PatternforCrunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à USER PASSWORD PROFILER.
        /// </summary>
        internal static string profiler {
            get {
                return ResourceManager.GetString("profiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Random.
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Would you a repeating of character ?.
        /// </summary>
        internal static string Repetition {
            get {
                return ResourceManager.GetString("Repetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RETURN    MAIN MENU.
        /// </summary>
        internal static string ReturnMainMenu {
            get {
                return ResourceManager.GetString("ReturnMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Want to reverse the pattern ?.
        /// </summary>
        internal static string ReversePatern {
            get {
                return ResourceManager.GetString("ReversePatern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to save the output to a file.
        /// </summary>
        internal static string SaveCharsetInFilesTxt {
            get {
                return ResourceManager.GetString("SaveCharsetInFilesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You want to compress them into zip file.
        /// </summary>
        internal static string SaveCharsetInFilesZip {
            get {
                return ResourceManager.GetString("SaveCharsetInFilesZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CRISIS CLIENT/SERVER BRUTE FORCER.
        /// </summary>
        internal static string serverMenu {
            get {
                return ResourceManager.GetString("serverMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is the size of a backup file in MB :.
        /// </summary>
        internal static string SizeFile {
            get {
                return ResourceManager.GetString("SizeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is the size the passwords : .
        /// </summary>
        internal static string SizeOfWorld {
            get {
                return ResourceManager.GetString("SizeOfWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SWEDISH.
        /// </summary>
        internal static string swedish {
            get {
                return ResourceManager.GetString("swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SYLLABLE FR.
        /// </summary>
        internal static string syllable_fr {
            get {
                return ResourceManager.GetString("syllable_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TRANSFORMING WORDLIST.
        /// </summary>
        internal static string transformWordlist {
            get {
                return ResourceManager.GetString("transformWordlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ROUTER / BOX WIFI.
        /// </summary>
        internal static string WIFI {
            get {
                return ResourceManager.GetString("WIFI", resourceCulture);
            }
        }
    }
}
