//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crisis.Core.Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr_Fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_Fr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("crisis.Core.Lang.fr-Fr", typeof(fr_Fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PRECEDENT.
        /// </summary>
        internal static string _return {
            get {
                return ResourceManager.GetString("_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous ajouter des chiffre [i.e. 0 à 9] Y/[N] :.
        /// </summary>
        internal static string AddNumber {
            get {
                return ResourceManager.GetString("AddNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Voulez-vous ajouter des caractère spéciaux ? Y/[N] :  .
        /// </summary>
        internal static string AddSpecialChar {
            get {
                return ResourceManager.GetString("AddSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Après.
        /// </summary>
        internal static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avant.
        /// </summary>
        internal static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avec quel category voulez-vous travailler : .
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous spécifier une chaîne de fin ?.
        /// </summary>
        internal static string ChangeEndblockPattern {
            get {
                return ResourceManager.GetString("ChangeEndblockPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ecrire la chaîne de fin :.
        /// </summary>
        internal static string ChangeEndblockPattern1 {
            get {
                return ResourceManager.GetString("ChangeEndblockPattern1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous spécifier une chaîne de départ ?.
        /// </summary>
        internal static string ChangeStartblockPattern {
            get {
                return ResourceManager.GetString("ChangeStartblockPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ecrire la chaîne de départ :.
        /// </summary>
        internal static string ChangeStartblockPattern1 {
            get {
                return ResourceManager.GetString("ChangeStartblockPattern1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CARACTERE MINUSCULES.
        /// </summary>
        internal static string CHARACTERLOWERCASE {
            get {
                return ResourceManager.GetString("CHARACTERLOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CARACTERE MAJUSCULES.
        /// </summary>
        internal static string CHARACTERUPPERCASE {
            get {
                return ResourceManager.GetString("CHARACTERUPPERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CARACTERE MAJUSCULES &amp; MINUSCULES.
        /// </summary>
        internal static string CHARACTERUPPERCASELOWERCASE {
            get {
                return ResourceManager.GetString("CHARACTERUPPERCASELOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Écrivez le modèle de votre choix : .
        /// </summary>
        internal static string charset {
            get {
                return ResourceManager.GetString("charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CREER UNE WORDLIST.
        /// </summary>
        internal static string createWordlist {
            get {
                return ResourceManager.GetString("createWordlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PERSONNALISER.
        /// </summary>
        internal static string CUSTOM {
            get {
                return ResourceManager.GetString("CUSTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CYRILLIQUE.
        /// </summary>
        internal static string cyrillic {
            get {
                return ResourceManager.GetString("cyrillic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Appuyer sur Entré ou Echap.
        /// </summary>
        internal static string EnterOrEchap {
            get {
                return ResourceManager.GetString("EnterOrEchap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   S&apos;il vous plaît entrer le mot    .
        /// </summary>
        internal static string EnterWorld {
            get {
                return ResourceManager.GetString("EnterWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à QUITTER.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incrémentation.
        /// </summary>
        internal static string Increment {
            get {
                return ResourceManager.GetString("Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Appuyé sur la touche Echappe (Esc) pour quitter ou sur Entré pour continuer  :.
        /// </summary>
        internal static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous voulez mélanger le modèle ?.
        /// </summary>
        internal static string MixPatern {
            get {
                return ResourceManager.GetString("MixPatern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NOMBRE.
        /// </summary>
        internal static string NUMBER {
            get {
                return ResourceManager.GetString("NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Entrez le nom et le chemin de votre fichier : .
        /// </summary>
        internal static string Patch {
            get {
                return ResourceManager.GetString("Patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dans quel dossier vous voulez sauvegarder les fichiers ? : .
        /// </summary>
        internal static string PathOfBuckupFiles {
            get {
                return ResourceManager.GetString("PathOfBuckupFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir confirmer l&apos;enregistrement à l&apos;intérieur de.
        /// </summary>
        internal static string PathOfBuckupFiles1 {
            get {
                return ResourceManager.GetString("PathOfBuckupFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modéle pour Crunch.
        /// </summary>
        internal static string PatternforCrunch {
            get {
                return ResourceManager.GetString("PatternforCrunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PROFIL DE MOT DE PASSE D&apos;UN UTILSATEUR.
        /// </summary>
        internal static string profiler {
            get {
                return ResourceManager.GetString("profiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aléatoire.
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Souhaitez-vous une répétition de caractère ? .
        /// </summary>
        internal static string Repetition {
            get {
                return ResourceManager.GetString("Repetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RETOUR AU MENU PRINCIPAL.
        /// </summary>
        internal static string ReturnMainMenu {
            get {
                return ResourceManager.GetString("ReturnMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous voulez inverser le  modèle ? .
        /// </summary>
        internal static string ReversePatern {
            get {
                return ResourceManager.GetString("ReversePatern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous enregistrer la sortie vers un fichier .
        /// </summary>
        internal static string SaveCharsetInFilesTxt {
            get {
                return ResourceManager.GetString("SaveCharsetInFilesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous voulez les compresser dans un fichier zip .
        /// </summary>
        internal static string SaveCharsetInFilesZip {
            get {
                return ResourceManager.GetString("SaveCharsetInFilesZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CLIENT CRISIS / SERVEUR CRISIS BRUTE FORCEUR.
        /// </summary>
        internal static string serverMenu {
            get {
                return ResourceManager.GetString("serverMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quelle est la taille d&apos;un fichier de sauvegarde en Mo : .
        /// </summary>
        internal static string SizeFile {
            get {
                return ResourceManager.GetString("SizeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quelle est la taille des mots de passe à générer  : .
        /// </summary>
        internal static string SizeOfWorld {
            get {
                return ResourceManager.GetString("SizeOfWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CARACTÈRES SPÉCIAUX.
        /// </summary>
        internal static string SPECIAL {
            get {
                return ResourceManager.GetString("SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SUÉDOIS.
        /// </summary>
        internal static string swedish {
            get {
                return ResourceManager.GetString("swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SYLLABE.
        /// </summary>
        internal static string syllable_fr {
            get {
                return ResourceManager.GetString("syllable_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TRANSFORMER DES FICHIERS DE WORDLIST.
        /// </summary>
        internal static string transformWordlist {
            get {
                return ResourceManager.GetString("transformWordlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ROUTEUR / BOX WIFI.
        /// </summary>
        internal static string WIFI {
            get {
                return ResourceManager.GetString("WIFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  En cours d&apos;execution, patienté svp !.
        /// </summary>
        internal static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
